export type ResumePreviewLayout = "classic" | "modern";

export type ResumePreviewTemplateClasses = {
  layout: ResumePreviewLayout;
  root: string;
  empty: string;
  header: string;
  name: string;
  professionalTitle: string;
  contact: string;
  contactDivider: string;
  contactItem: string;
  contactIcon: string;
  contactLink: string;
  section: string;
  sectionTitleRow: string;
  sectionIcon: string;
  sectionTitle: string;
  sectionBody: string;
  bodyText: string;
  entryBlock: string;
  entryTitleRow: string;
  entryDot: string;
  entryTitle: string;
  entrySubtitle: string;
  entrySubtitleFallback: string;
  metaLine: string;
  description: string;
  skillChip: string;
  skillsList: string;
  list: string;
  linkLine: string;
  linkLabel: string;
  linkMuted: string;
  linkUrl: string;
  linksList: string;
  certTitle: string;
  certMeta: string;
};
